# Generated by Django 5.0.7 on 2025-01-02 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50, unique=True)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('company_name', models.CharField(blank=True, default='AR. DJ Hardware Trading', max_length=255, null=True)),
                ('company_address', models.TextField(blank=True, default='street bergal maligaya park, 77 Bautista, Caloocan, Metro Manila', null=True)),
                ('contact_no', models.CharField(blank=True, default='09123456789', max_length=15, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_amount_with_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cash_tendered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Voided', 'Voided')], default='Pending', max_length=20)),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfficialReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50, unique=True)),
                ('company_name', models.CharField(blank=True, default='AR. DJ Hardware Trading', max_length=255, null=True)),
                ('company_address', models.TextField(blank=True, default='street bergal maligaya park, 77 Bautista, Caloocan, Metro Manila', null=True)),
                ('receipt_date', models.DateField(auto_now_add=True)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_amount_with_vat', models.DecimalField(decimal_places=2, max_digits=20)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_receipts', to=settings.AUTH_USER_MODEL)),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_receipt', to='pos_view.salesinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('measurement', models.CharField(blank=True, default='No Measurement', max_length=50, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='pos_view.salesinvoice')),
            ],
        ),
    ]
