# Generated by Django 5.0.7 on 2024-11-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_view', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='total_amount_with_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
