# Generated by Django 5.0.7 on 2024-12-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_view', '0005_officialreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='measurement',
            field=models.CharField(blank=True, default='No Measurement', max_length=50, null=True),
        ),
    ]
