# Generated by Django 5.0.7 on 2024-07-30 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_view', '0004_rename_reason_for_waste_wasteproduct_supplier_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='inventory_view.product')),
            ],
        ),
    ]
