# Generated by Django 5.0.7 on 2024-07-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstance',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
