# Generated by Django 5.0.7 on 2024-08-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_view', '0002_productinstance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstance',
            name='reorder_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
