# Generated by Django 5.0.7 on 2024-08-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_view', '0003_productinstance_reorder_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstance',
            name='reorder_level',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
