# Generated by Django 5.0.7 on 2024-11-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_view', '0004_alter_productinstance_reorder_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstance',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
