# Generated by Django 5.0.7 on 2025-01-02 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.CharField(max_length=20, unique=True)),
                ('buyer_company_name', models.CharField(default='AR. DJ Hardware Trading', max_length=255, null=True)),
                ('buyer_address', models.TextField(default='street bergal maligaya park, 77 Bautista, Caloocan, Metro Manila', null=True)),
                ('buyer_contact', models.CharField(max_length=100, null=True)),
                ('supplier_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_company_address', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_company_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('date_ordered', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total_amount_with_vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepared_by_employee', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=25, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('measurement', models.CharField(max_length=50, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement_view.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='RequestQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_company_name', models.CharField(default='AR. DJ Hardware Trading', max_length=255, null=True)),
                ('buyer_address', models.CharField(default='street bergal maligaya park, 77 Bautista, Caloocan, Metro Manila', max_length=255, null=True)),
                ('buyer_contact', models.CharField(max_length=100, null=True)),
                ('quotation_no', models.CharField(max_length=50, unique=True)),
                ('quote_valid_until', models.DateField(null=True)),
                ('date_prepared', models.DateField(auto_now_add=True)),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total_amount_with_vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('status', models.CharField(default='Ongoing', max_length=50, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestQuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('measurement', models.CharField(max_length=50, null=True)),
                ('price_valid_until', models.DateField(null=True)),
                ('request_quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement_view.requestquotation')),
            ],
        ),
    ]
