# Generated by Django 5.0.7 on 2024-10-18 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_view', '0002_alter_requestquotation_date_prepared_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestquotation',
            name='total_amount',
        ),
    ]
