# Generated by Django 5.0.7 on 2024-10-26 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_view', '0003_remove_requestquotation_total_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_company_name', models.CharField(max_length=255)),
                ('buyer_address', models.TextField()),
                ('buyer_contact', models.CharField(max_length=255)),
                ('quotation_no', models.CharField(max_length=50)),
                ('prepared_by', models.CharField(max_length=255)),
                ('quote_valid_until', models.DateField()),
                ('date_submitted', models.DateField()),
                ('terms_and_conditions', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationSubmissionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quotation_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement_view.quotationsubmission')),
            ],
        ),
    ]
