# Generated by Django 5.0.7 on 2024-10-27 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_view', '0004_quotationsubmission_quotationsubmissionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationsubmission',
            name='date_submitted',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='requestquotationitem',
            name='request_quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement_view.requestquotation'),
        ),
    ]
