# Generated by Django 5.0.7 on 2024-10-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_view', '0007_alter_purchaseorder_date_ordered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product',
            field=models.CharField(max_length=255),
        ),
    ]
