# Generated by Django 5.0.7 on 2024-10-31 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_view', '0009_alter_purchaseorder_buyer_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='po_no',
            new_name='quotation_no',
        ),
    ]
