# Generated by Django 5.0.7 on 2024-11-01 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_view', '0010_rename_po_no_purchaseorder_quotation_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationsubmissionitem',
            name='quotation_submission',
        ),
        migrations.DeleteModel(
            name='QuotationSubmission',
        ),
        migrations.DeleteModel(
            name='QuotationSubmissionItem',
        ),
    ]
