# Generated by Django 5.0.7 on 2024-11-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_view', '0013_rename_prepared_by_requestquotation_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestquotation',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requestquotation',
            name='status',
            field=models.CharField(default='Pending Approval', max_length=50),
        ),
        migrations.AlterField(
            model_name='requestquotation',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
