# Generated by Django 5.0.7 on 2024-11-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_view', '0014_alter_requestquotation_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestquotation',
            name='buyer_address',
            field=models.CharField(default='street bergal maligaya park, 77 Bautista, Caloocan, Metro Manila', max_length=255),
        ),
        migrations.AlterField(
            model_name='requestquotation',
            name='buyer_company_name',
            field=models.CharField(default='AR. DJ Hardware Trading', max_length=255),
        ),
    ]
