# Generated by Django 5.0.7 on 2024-11-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_view', '0015_alter_requestquotation_buyer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestquotation',
            name='buyer_address',
            field=models.CharField(blank=True, default='street bergal maligaya park, 77 Bautista, Caloocan, Metro Manila', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requestquotation',
            name='buyer_company_name',
            field=models.CharField(blank=True, default='AR. DJ Hardware Trading', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requestquotation',
            name='status',
            field=models.CharField(blank=True, default='Pending Approval', max_length=50, null=True),
        ),
    ]
