# Generated by Django 5.0.7 on 2024-11-23 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_view', '0016_alter_requestquotation_buyer_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='buyer_address',
            field=models.TextField(blank=True, default='street bergal maligaya park, 77 Bautista, Caloocan, Metro Manila', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='buyer_company_name',
            field=models.CharField(blank=True, default='AR. DJ Hardware Trading', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestquotation',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
