# Generated by Django 5.0.7 on 2024-12-05 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_view', '0017_alter_purchaseorder_buyer_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='product',
            new_name='product_name',
        ),
    ]
