# Generated by Django 5.0.7 on 2024-12-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_view', '0018_rename_product_purchaseorderitem_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
