# Generated by Django 5.0.7 on 2024-12-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_view', '0019_alter_purchaseorderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='total_amount_with_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
