# Generated by Django 5.0.7 on 2024-12-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_view', '0020_purchaseorder_total_amount_with_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
