# Generated by Django 5.0.7 on 2024-12-07 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_view', '0021_alter_purchaseorderitem_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='total_amount_with_tax',
            new_name='total_amount_with_vat',
        ),
    ]
