# Generated by Django 5.0.7 on 2024-12-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_view', '0022_rename_total_amount_with_tax_purchaseorder_total_amount_with_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestquotation',
            name='status',
            field=models.CharField(blank=True, default='Ongoing', max_length=50, null=True),
        ),
    ]
