# Generated by Django 5.0.7 on 2024-12-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_view', '0023_alter_requestquotation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestquotationitem',
            name='price_valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
