# Generated by Django 5.0.7 on 2024-12-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_view', '0024_requestquotationitem_price_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestquotation',
            name='quote_valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestquotationitem',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
