# Generated by Django 5.0.7 on 2024-12-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_view', '0025_alter_requestquotation_quote_valid_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestquotation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='requestquotation',
            name='total_amount_with_vat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
