# Generated by Django 5.0.7 on 2024-12-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_view', '0026_requestquotation_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
    ]
