# Generated by Django 5.0.7 on 2024-12-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_view', '0028_alter_requestquotationitem_price_valid_until_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestquotation',
            name='approved_by',
        ),
        migrations.AlterField(
            model_name='requestquotation',
            name='buyer_address',
            field=models.CharField(default='street bergal maligaya park, 77 Bautista, Caloocan, Metro Manila', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requestquotation',
            name='buyer_company_name',
            field=models.CharField(default='AR. DJ Hardware Trading', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requestquotation',
            name='buyer_contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requestquotation',
            name='quote_valid_until',
            field=models.DateField(null=True),
        ),
    ]
