# Generated by Django 5.0.7 on 2024-12-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_view', '0029_remove_requestquotation_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestquotation',
            name='status',
            field=models.CharField(default='Ongoing', max_length=50, null=True),
        ),
    ]
