# Generated by Django 5.0.7 on 2024-12-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_view', '0030_alter_requestquotation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='measurement',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='requestquotationitem',
            name='measurement',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='buyer_address',
            field=models.TextField(default='street bergal maligaya park, 77 Bautista, Caloocan, Metro Manila', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='buyer_company_name',
            field=models.CharField(default='AR. DJ Hardware Trading', max_length=255, null=True),
        ),
    ]
