# Generated by Django 5.0.7 on 2024-12-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_view', '0033_alter_purchaseorder_prepared_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_company_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_company_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
