# Generated by Django 5.0.7 on 2025-01-02 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement_view', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('buyer_company_name', models.CharField(default='AR. DJ Hardware Trading', max_length=255)),
                ('buyer_address', models.TextField(default='street bergal maligaya park, 77 Bautista, Caloocan, Metro Manila')),
                ('supplier_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_company_address', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_company_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('date_issued', models.DateField(auto_now_add=True, null=True)),
                ('total_amount_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_amount_payable_with_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=50, null=True)),
                ('purchase_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='procurement_view.purchaseorder')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('measurement', models.CharField(max_length=50, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supplier_view.purchaseinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_company_name', models.CharField(default='AR. DJ Hardware Trading', max_length=255)),
                ('buyer_address', models.TextField(default='street bergal maligaya park, 77 Bautista, Caloocan, Metro Manila')),
                ('buyer_contact', models.CharField(max_length=255)),
                ('supplier_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_company_address', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_company_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('quotation_no', models.CharField(blank=True, max_length=50, null=True)),
                ('prepared_by', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_amount_with_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('quote_valid_until', models.DateField()),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('terms_and_conditions', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('request_quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_submissions', to='procurement_view.requestquotation')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationSubmissionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('measurement', models.CharField(max_length=50, null=True)),
                ('price_valid_until', models.DateField(null=True)),
                ('quotation_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supplier_view.quotationsubmission')),
            ],
        ),
    ]
