# Generated by Django 5.0.7 on 2024-11-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationsubmission',
            name='quotation_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
