# Generated by Django 5.0.7 on 2024-11-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_view', '0003_remove_quotationsubmission_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationsubmission',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
