# Generated by Django 5.0.7 on 2024-11-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_view', '0006_alter_purchaseinvoice_date_issued_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='date_issued',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
