# Generated by Django 5.0.7 on 2024-11-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_view', '0007_alter_purchaseinvoice_date_issued'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='terms_and_condition',
        ),
    ]
