# Generated by Django 5.0.7 on 2024-11-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_view', '0009_alter_purchaseinvoice_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseinvoiceitem',
            old_name='invoice',
            new_name='purchase_invoice',
        ),
    ]
