# Generated by Django 5.0.7 on 2024-12-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_view', '0011_purchaseinvoice_total_amount_payable_with_vat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='price_valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
