# Generated by Django 5.0.7 on 2024-12-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_view', '0015_alter_quotationsubmission_buyer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='measurement',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotationsubmissionitem',
            name='measurement',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
