# Generated by Django 5.0.7 on 2024-12-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_view', '0016_purchaseinvoiceitem_measurement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationsubmission',
            name='supplier_contact',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
