# Generated by Django 5.0.7 on 2024-12-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_view', '0017_quotationsubmission_supplier_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationsubmissionitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
