# Generated by Django 5.0.7 on 2024-12-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_view', '0018_alter_quotationsubmissionitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationsubmissionitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
