# Generated by Django 5.0.7 on 2024-12-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_view', '0019_alter_quotationsubmissionitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationsubmissionitem',
            name='price_valid_until',
            field=models.DateField(null=True),
        ),
    ]
