# Generated by Django 5.0.7 on 2024-12-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_view', '0022_alter_quotationsubmissionitem_price_valid_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationsubmissionitem',
            name='price_valid_until',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='quotationsubmissionitem',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quotationsubmissionitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
