# Generated by Django 5.0.7 on 2024-12-12 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_view', '0031_purchaseorderitem_measurement_and_more'),
        ('supplier_view', '0023_alter_quotationsubmissionitem_price_valid_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='purchase_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='procurement_view.purchaseorder'),
        ),
    ]
