# Generated by Django 5.0.7 on 2024-12-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_view', '0024_purchaseinvoice_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationsubmission',
            name='total_amount_payable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='quotationsubmission',
            name='total_amount_payable_with_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
