# Generated by Django 5.0.7 on 2024-12-12 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_view', '0025_quotationsubmission_total_amount_payable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationsubmission',
            old_name='total_amount_payable',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='quotationsubmission',
            old_name='total_amount_payable_with_vat',
            new_name='total_amount_with_vat',
        ),
    ]
