# Generated by Django 5.0.7 on 2024-12-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_view', '0026_rename_total_amount_payable_quotationsubmission_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='supplier_address',
        ),
        migrations.RemoveField(
            model_name='quotationsubmission',
            name='supplier_contact',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier_company_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier_company_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotationsubmission',
            name='supplier_company_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotationsubmission',
            name='supplier_company_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotationsubmission',
            name='supplier_company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
