# Generated by Django 5.0.7 on 2024-12-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_view', '0027_remove_purchaseinvoice_supplier_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='buyer_address',
            field=models.TextField(default='street bergal maligaya park, 77 Bautista, Caloocan, Metro Manila'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='buyer_company_name',
            field=models.CharField(default='AR. DJ Hardware Trading', max_length=255),
        ),
    ]
