# Generated by Django 5.0.7 on 2024-07-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_view', '0002_alter_product_batch_number_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(max_length=50, null=True, unique=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('reason_for_waste', models.CharField(max_length=100, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
