# Generated by Django 5.0.7 on 2024-07-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_view', '0003_wasteproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wasteproduct',
            old_name='reason_for_waste',
            new_name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_restock_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reorder_level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_contact',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty_period',
        ),
        migrations.RemoveField(
            model_name='wasteproduct',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='wasteproduct',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wasteproduct',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wasteproduct',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wasteproduct',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wasteproduct',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wasteproduct',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wasteproduct',
            name='material',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wasteproduct',
            name='unit_of_measurement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wasteproduct',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
