# Generated by Django 5.0.7 on 2024-09-22 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_view', '0006_delete_wasteproduct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unit_price',
            new_name='cost_price',
        ),
    ]
