# Generated by Django 5.0.7 on 2024-10-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_view', '0007_rename_unit_price_product_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Wasted', 'Wasted')], default='Active', max_length=50),
        ),
    ]
