# Generated by Django 5.0.7 on 2024-10-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_view', '0010_alter_product_supplier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
