# Generated by Django 5.0.7 on 2024-10-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_view', '0015_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Wasted', 'Wasted')], default='Active', max_length=50),
        ),
    ]
