# Generated by Django 5.0.7 on 2024-11-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_view', '0019_alter_product_status_wasteproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='wasteproduct',
            name='date_wasted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
