# Generated by Django 5.0.7 on 2024-11-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_view', '0022_alter_wasteproduct_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wasteproduct',
            old_name='user',
            new_name='employee',
        ),
    ]
