# Generated by Django 5.0.7 on 2024-12-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_view', '0026_alter_product_category_alter_product_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measurement',
            field=models.CharField(blank=True, default='No Measurement', max_length=50, null=True),
        ),
    ]
