# Generated by Django 5.0.7 on 2024-07-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('employee', 'Employee'), ('supplier', 'Supplier'), ('unkown', 'Unkown')], default='unknown', max_length=10),
        ),
    ]
