# Generated by Django 5.0.7 on 2024-09-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_view', '0002_alter_userpermission_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='role',
            field=models.CharField(choices=[(None, 'Manager'), (None, 'Employee'), (None, 'Supplier'), (None, 'Unkown')], default='unknown', max_length=10),
        ),
    ]
