# Generated by Django 5.0.7 on 2024-10-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_view', '0004_alter_userpermission_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='role',
            field=models.CharField(choices=[('manager', 'manager'), ('employee', 'manager'), ('supplier', 'manager'), ('unkown', 'manager')], default='unknown', max_length=10),
        ),
    ]
