# Generated by Django 5.0.7 on 2024-11-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_view', '0005_alter_userpermission_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='role',
            field=models.CharField(choices=[('manager', 'manager'), ('employee', 'employee'), ('supplier', 'supplier'), ('unkown', 'unkown')], default='unknown', max_length=10),
        ),
    ]
