# Generated by Django 5.0.7 on 2024-12-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_view', '0007_employee_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='buyer_company_contact',
        ),
        migrations.AlterField(
            model_name='employee',
            name='buyer_company_address',
            field=models.TextField(blank=True, default='street bergal maligaya park, 77 Bautista, Caloocan, Metro Manila'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='buyer_company_name',
            field=models.CharField(blank=True, default='AR. DJ Hardware Trading', max_length=255),
        ),
    ]
