# Generated by Django 5.0.7 on 2024-12-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_view', '0008_remove_employee_buyer_company_contact_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
