# Generated by Django 5.0.7 on 2024-12-27 11:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_view', '0010_userprofile_delete_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='CompanyProfile',
        ),
    ]
