# Generated by Django 5.0.7 on 2024-12-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_view', '0013_alter_companyprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_contact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
